name = "stat-tools-worker"
main = "src/workers/signed-url/index.mjs"
compatibility_date = "2025-09-05"
account_id = "00000000000000000000000000000000" # REPLACE with your real Account ID
workers_dev = true

# Uncomment and set for production env
# route = "example.com/*"
# zone_id = "YOUR_ZONE_ID"

[env.production]
# route = "example.com/*"
# zone_id = "YOUR_ZONE_ID"

# NOTE: For security, set SIGN_SECRET via `wrangler secret put SIGN_SECRET`
// NOTE: Do not define secrets in [vars]. Use `wrangler secret put SIGN_SECRET` instead.

[r2_buckets]
export_bucket = { binding = "EXPORT_BUCKET", bucket_name = "stat-tools-exports" }
