-- Seed glossary terms
-- Created: 2025-09-17
-- Description: Populates glossary_terms table with statistical definitions

-- Insert glossary terms dataINSERT INTO glossary_terms VALUES(1,'mean','Mean','The average of a set of numbers','Mean (arithmetic mean) is the sum of all values divided by the number of values. It represents the central tendency of a dataset and is one of the most commonly used statistical measures.',NULL,'2025-09-16 03:05:53','2025-09-16 03:05:53');
INSERT INTO glossary_terms VALUES(2,'median','Median','The middle value when data is ordered','Median is the middle value in an ordered dataset. For odd numbers of data points, it''s the middle value. For even numbers, it''s the average of the two middle values. Median is less affected by outliers than mean.',NULL,'2025-09-16 03:05:53','2025-09-16 03:05:53');
INSERT INTO glossary_terms VALUES(3,'mode','Mode','The most frequently occurring value','Mode is the value that appears most frequently in a dataset. A dataset can have no mode, one mode (unimodal), or multiple modes (bimodal, multimodal). Mode is useful for both numerical and categorical data.',NULL,'2025-09-16 03:05:53','2025-09-16 03:05:53');
INSERT INTO glossary_terms VALUES(4,'standard-deviation','Standard Deviation','Measure of data spread around the mean','Standard deviation measures how spread out data points are from the mean. A small standard deviation indicates data points are close to the mean, while a large standard deviation indicates more spread. It''s the square root of variance.',NULL,'2025-09-16 03:05:53','2025-09-16 03:05:53');
INSERT INTO glossary_terms VALUES(5,'variance','Variance','Average of squared differences from the mean','Variance measures the variability of data points from the mean. It''s calculated as the average of squared differences from the mean. Sample variance uses n-1 in the denominator (Bessel''s correction) while population variance uses n.',NULL,'2025-09-16 03:05:53','2025-09-16 03:05:53');
INSERT INTO glossary_terms VALUES(6,'range','Range','Difference between maximum and minimum values','Range is the simplest measure of variability, calculated as the difference between the largest and smallest values in a dataset. While easy to calculate, it''s sensitive to outliers and doesn''t account for the distribution of values between extremes.',NULL,'2025-09-16 03:05:53','2025-09-16 03:05:53');
INSERT INTO glossary_terms VALUES(7,'weighted-mean','Weighted Mean','Average that accounts for different importance of values','Weighted mean (weighted average) gives different weights to different values based on their importance or frequency. It''s calculated by multiplying each value by its weight, summing these products, and dividing by the sum of weights.',NULL,'2025-09-16 03:05:53','2025-09-16 03:05:53');
INSERT INTO glossary_terms VALUES(8,'gpa','GPA','Grade Point Average for academic performance','GPA (Grade Point Average) is a standardized way to measure academic achievement. It''s calculated by assigning point values to letter grades, multiplying by credit hours, and dividing by total credit hours attempted.',NULL,'2025-09-16 03:05:53','2025-09-16 03:05:53');
INSERT INTO glossary_terms VALUES(9,'unweighted-gpa','Unweighted GPA','Simple GPA without difficulty adjustments','Unweighted GPA treats all courses equally regardless of difficulty level. Standard grades (A=4.0, B=3.0, C=2.0, D=1.0, F=0.0) are used without additional points for honors, AP, or advanced courses.',NULL,'2025-09-16 03:05:53','2025-09-16 03:05:53');
INSERT INTO glossary_terms VALUES(10,'weighted-gpa','Weighted GPA','GPA adjusted for course difficulty','Weighted GPA gives additional points for more challenging courses like Honors, AP, or IB classes. This system recognizes that advanced courses require more effort and provides a more comprehensive view of academic achievement.',NULL,'2025-09-16 03:05:53','2025-09-16 03:05:53');
INSERT INTO glossary_terms VALUES(11,'percentile','Percentile','Value below which a percentage of data falls','Percentile indicates the value below which a certain percentage of observations fall. For example, the 75th percentile is the value below which 75% of the data points lie. Percentiles are useful for understanding relative position in a dataset.',NULL,'2025-09-16 03:05:53','2025-09-16 03:05:53');
INSERT INTO glossary_terms VALUES(12,'confidence-interval','Confidence Interval','Range of plausible values for a parameter','Confidence interval provides a range of values that likely contains the true population parameter. A 95% confidence interval means that if we repeated the sampling process many times, 95% of the intervals would contain the true parameter value.',NULL,'2025-09-16 03:05:53','2025-09-16 03:05:53');
INSERT INTO glossary_terms VALUES(13,'percent-error','Percent Error','Measure of accuracy in measurements or calculations','Percent error quantifies the accuracy of a measured or calculated value compared to the true or accepted value. It''s calculated as the absolute difference between measured and true values, divided by the true value, then multiplied by 100%.',NULL,'2025-09-16 03:05:53','2025-09-16 03:05:53');
INSERT INTO glossary_terms VALUES(14,'descriptive-statistics','Descriptive Statistics','Statistical methods for summarizing and describing data characteristics','Statistical methods used to describe and summarize data characteristics, including measures of central tendency (mean, median, mode), dispersion (standard deviation, variance, range), and distribution shape. Descriptive statistics provide a concise summary of sample data without making inferences about the larger population. Examples include calculating the average test score for a class, finding the spread of housing prices in a neighborhood, or determining the most common customer rating.',NULL,'2025-09-16 04:47:51','2025-09-16 04:47:51');
INSERT INTO glossary_terms VALUES(15,'central-tendency','Central Tendency','Statistical measures that identify the center or typical value of a dataset','Statistical measures that describe the center position of a dataset, indicating the typical or average value around which data points cluster. The three main measures are: mean (arithmetic average), median (middle value when data is ordered), and mode (most frequently occurring value). Central tendency helps identify the "typical" case and provides a single value that represents the entire dataset. The choice between measures depends on data distribution and the presence of outliers.',NULL,'2025-09-16 04:47:51','2025-09-16 04:47:51');
INSERT INTO glossary_terms VALUES(16,'dispersion','Dispersion','Statistical measures that describe how spread out or variable data points are','Statistical measures that describe the spread or variability of data points, indicating how much values deviate from the central value. Common measures include standard deviation (average distance from mean), variance (squared standard deviation), range (difference between maximum and minimum), and interquartile range (spread of middle 50% of data). High dispersion indicates data points are spread widely from the center, while low dispersion indicates data points cluster closely around the central value.',NULL,'2025-09-16 04:47:51','2025-09-16 04:47:51');
INSERT INTO glossary_terms VALUES(17,'sample-vs-population','Sample vs Population','Distinction between complete datasets (population) and subsets (samples)','Population refers to the complete set of all objects, individuals, or measurements being studied, while sample refers to a subset selected from the population for analysis. Population parameters describe characteristics of the entire group, while sample statistics estimate these characteristics. For example, surveying all US college students represents the population, while surveying 1,000 randomly selected students represents a sample. Statistical inference uses sample data to make conclusions about population parameters, requiring careful sampling methods to ensure representativeness.',NULL,'2025-09-16 04:47:51','2025-09-16 04:47:51');
INSERT INTO glossary_terms VALUES(18,'credit-system','Credit System','Educational framework that assigns units to courses based on workload and difficulty','Educational system that assigns credit units (credit hours) to courses based on contact time, workload, and academic difficulty. Credits determine course weight in GPA calculations and graduation requirements. Typically, one credit represents one hour of class time per week over a semester. For example, a 3-credit course meets three hours weekly and carries three times the GPA weight of a 1-credit course. Credit systems enable standardized measurement of academic progress and fair comparison of student workloads across different courses and institutions.',NULL,'2025-09-16 04:47:51','2025-09-16 04:47:51');
INSERT INTO glossary_terms VALUES(19,'grade-point-average','Grade Point Average (GPA)','Numerical representation of academic performance calculated from letter grades','Academic performance indicator calculated by converting letter grades to numerical points and computing the weighted average based on credit hours. In the standard 4.0 scale: A=4.0, B=3.0, C=2.0, D=1.0, F=0.0. GPA calculation: sum of (grade points × credit hours) divided by total credit hours. For example, an A in a 3-credit course contributes 12 grade points (4.0 × 3). GPAs provide standardized comparison of academic achievement and are crucial for college admissions, scholarships, and academic standing.',NULL,'2025-09-16 04:47:51','2025-09-16 04:47:51');
INSERT INTO glossary_terms VALUES(20,'course-weighting','Course Weighting','System of adjusting course impact on GPA based on difficulty and type','System of adjusting a course''s contribution to overall GPA based on its type, difficulty level, and academic rigor. Advanced courses (AP, IB, Honors) receive higher weights to reflect increased challenge. For example: AP courses weighted 1.2 (A=4.8), Honors courses weighted 1.1 (A=4.4), Regular courses weighted 1.0 (A=4.0). This system encourages students to take challenging coursework while ensuring fair GPA representation. Weighted GPAs can exceed 4.0, while unweighted GPAs cap at 4.0 regardless of course difficulty.',NULL,'2025-09-16 04:47:51','2025-09-16 04:47:51');
