name: Docs Check

on:
  pull_request:
    paths:
      - 'specs/FRS/**'
      - 'docs/**'
      - 'scripts/**'

jobs:
  docs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run docs-check
